### ISSUE TITLE
For iteration

### ISSUE THREAD

**Issue by R2SB** [liucharlie213/Rorys-Live-Karoake#6]
## Function
- The "Browse Songs" button doesn't do anything
- I changed the tipping link to venmo://paycharge?txn=pay&recipients=RoryChambers which works on a phone because it links straight to the app, but it doesn't work on desktop. not a huge deal, but if there’s a way to have a “if this link doesn’t work go to that link”, that’d be good.
- can we add a songID value in the CSV so I can keep track of the order songs get added? I could use that to keep an automatically generated "most recent" playlist (see  #8 for playlist examples. Pretty cool) 
- It’d be cool if the search bar had a “clear search” button
- when we search, the list doesn't automatically scroll to the top of the results 
- It’d be cool if clicking the “sort by” buttons alternated A-Z and Z-A. Currently, the Tags button shows the un-tagged things first, which is unfortunately most of them.
- Some of the cover images aren’t right, can I just browse for them manually somewhere?
- it’d also be cool if the “submit” button on the request form changed to “got it!” or something like that

## Layout
- the tip jar button is pretty small, and at my regular gig I usually make almost as much in tips as I get paid, so it’s worth making it easier to see.
- browsing on an iPad cuts off the sides of the title (resize issue)
- now that I see the backend, I understand why the layout is the way it is (one thing in line underneath the other) but if it’s possible to put the heading and picture carousel side-by-side when on a larger display, that’d be cool.

**Comment by R2SB** [comment]
I figured out why that search broke when I changed the CSV fileh a few weeks ago. There was a blank line at the bottom of the file; deleting it fixed the problem.

**Comment by liucharlie213** [comment]
Completed:
- fixed "Browse Songs" button
- tipping link runs venmo if that works, else it runs cashapp
- clear search bar button added
- song list scrolls to the top automatically when searching
- sorting by tags shows tagged songs first
- submit button changed to got it

**Comment by R2SB** [comment]
requesting a song makes the songlist go blank in my localhost version EDIT: This doesn't happen anymore. Must have been my localhost having a tantrum

**Comment by R2SB** [comment]
I worked on this a bit today, I forked the main git: https://github.com/R2SB/Rorys-Live-Karaoke-2024.git

- This now has the most recent CSV songlist, I added the SongID column to it
- All the songs have artwork now
- I edited some text/layout
- re-enabled the Carousel component, renamed it to 10mostrecent.csv, I have a python script to generate that from the main CSV when i update it.
- I made the icons bigger and more spaced out for drunk, fat thumbs.
- Changed the Venmo link just to venmo rather than Cashapp. In three years of doing this gig, I've never got a tip on Cashapp. Happy to be convinced to keep it though; gotta get that money.

### Issues
- The Difficulty colours aren't showing in the songlist for some reason
- Can we resize the Carousel to 1/2 the height?
- Of course, adding SongID to the CSV broke the search function. I just can't find where to fix it. I like that the column doesn't show up on the site though.

### Goals
- the title needs to resize/go to mobile layout once it hits 1040px wide - DONE
- I'd love to reduce the blank space between each component and tighten the whole page up, especially on desktop.
- I'd love to change the donate icon to something else; I don't know why that one makes me feel icky. I found the one you used on fontawesome, but the one I changed it to wasn't the same linewidth as the instagram/mail ones you have. Changing it to the hand with the heart is better.
- I deleted the "Rory's Live Karaoke" title, but I can see that it kind of needs to be there for the site header. I'll think about what to replace it with. 
- Can we make the Nav a persistent component as the page scrolls down so folks can click it to get to the top of the site? (also, so the tip button is permanently on-screen)
- Which component do I add a background image? - DONE-ish - need to update Landing with this
### Carousel
Rather than the current carousel, it'd be rad to have buttons that open and close lists. E.g. 80s pop, Bangers, Country, etc. Just squares that when clicked open like a navmenu with song titles on it. Those lists can be managed by separate CSVs

**Comment by liucharlie213** [comment]
CSV Notes:
- make sure all Columns follow a specific format
-
